type ProjectFields = {
  title: string
  description: string
  what: string
  learned: string
  why: string
}

export type ProjectContent = Record<'en' | 'vi' | 'et' | 'ru' | 'da' | 'tr' | 'zh' | 'pl' | 'fi' | 'sv' | 'tok', ProjectFields>

export type Project = {
  id: number
  content: ProjectContent
  tags: string[]
  status: "completed" | "in-progress" | "planned"
  category: "personal" | "academic" | "activism"
  hidden?: boolean
}

export const projects: Project[] = [
  {
    id: 1,
    content: {
      en: {
        title: "Economics research paper",
        description: "Analysis of wealth inequality trends in post-industrial economies",
        what: "A comprehensive research paper examining wealth distribution patterns across developed nations",
        learned: "Advanced statistical modeling and comparative economic analysis",
        why: "To understand systemic factors driving inequality and propose policy solutions",
      },
      vi: {
        title: "Nghiên cứu kinh tế",
        description: "Phân tích xu hướng bất bình đẳng tài sản trong các nền kinh tế hậu công nghiệp",
        what: "Một bài nghiên cứu toàn diện về mô hình phân phối tài sản ở các quốc gia phát triển",
        learned: "Mô hình thống kê nâng cao và phân tích kinh tế so sánh",
        why: "Để hiểu các yếu tố hệ thống thúc đẩy bất bình đẳng và đề xuất giải pháp chính sách",
      },
      et: {
        title: "Majandusuuringute artikkel",
        description: "Varalise ebavõrdsuse trendide analüüs postindustriaalsetes majandustes",
        what: "Kõikehõlmav uurimisartikkel, mis käsitleb varade jaotuse mustreid arenenud riikides",
        learned: "Täpsem statistiline modelleerimine ja võrdlev majandusanalüüs",
        why: "Süsteemsete ebavõrdsust põhjustavate tegurite mõistmiseks ja poliitikalahenduste pakkumiseks",
      },
      ru: {
        title: "Экономическое исследование",
        description: "Анализ тенденций имущественного неравенства в постиндустриальных экономиках",
        what: "Комплексное исследование моделей распределения богатства в развитых странах",
        learned: "Продвинутое статистическое моделирование и сравнительный экономический анализ",
        why: "Понять системные факторы, способствующие неравенству, и предложить политические решения",
      },
      da: {
        title: "Økonomisk forskningspaper",
        description: "Analyse af formueuligheds tendenser i postindustrielle økonomier",
        what: "En omfattende forskningsartikel, der undersøger formuefordelingsmønstre på tværs af udviklede nationer",
        learned: "Avanceret statistisk modellering og komparativ økonomisk analyse",
        why: "At forstå systemiske faktorer, der driver ulighed, og foreslå politiske løsninger",
      },
      tr: {
        title: "Ekonomi araştırma makalesi",
        description: "Post-endüstriyel ekonomilerde servet eşitsizliği eğilimlerinin analizi",
        what: "Gelişmiş ülkelerde servet dağılımı modellerini inceleyen kapsamlı bir araştırma makalesi",
        learned: "Gelişmiş istatistiksel modelleme ve karşılaştırmalı ekonomik analiz",
        why: "Eşitsizliği tetikleyen sistemik faktörleri anlamak ve politika çözümleri önermek",
      },
      zh: {
        title: "经济学研究论文",
        description: "后工业经济体财富不平等趋势分析",
        what: "一篇全面的研究论文，审视发达国家的财富分配模式",
        learned: "高级统计建模和比较经济分析",
        why: "理解推动不平等的系统性因素并提出政策解决方案",
      },
      pl: {
        title: "Artykuł badawczy z ekonomii",
        description: "Analiza trendów nierówności majątkowych w gospodarkach postindustrialnych",
        what: "Kompleksowy artykuł badawczy analizujący wzorce dystrybucji majątku w krajach rozwiniętych",
        learned: "Zaawansowane modelowanie statystyczne i porównawcza analiza ekonomiczna",
        why: "Aby zrozumieć systemowe czynniki napędzające nierówności i zaproponować rozwiązania polityczne",
      },
      fi: {
        title: "Taloustieteen tutkimuspaperi",
        description: "Varallisuuserojen trendien analyysi jälkiteollisissa talouksissa",
        what: "Kattava tutkimuspaperi, joka tarkastelee varallisuuden jakautumismalleja kehittyneissä maissa",
        learned: "Edistynyt tilastollinen mallinnus ja vertaileva taloudellinen analyysi",
        why: "Ymmärtää järjestelmällisiä tekijöitä, jotka ajavat eriarvoisuutta, ja ehdottaa poliittisia ratkaisuja",
      },
      sv: {
        title: "Ekonomisk forskningsartikel",
        description: "Analys av trender i förmögenhetsolikhet i postindustriella ekonomier",
        what: "En omfattande forskningsartikel som undersöker mönster för förmögenhetsfördelning i utvecklade nationer",
        learned: "Avancerad statistisk modellering och jämförande ekonomisk analys",
        why: "För att förstå systemiska faktorer som driver ojämlikhet och föreslå politiska lösningar",
      },
      tok: {
        title: "Economics research paper",
        description: "Analysis of wealth inequality trends in post-industrial economies",
        what: "A comprehensive research paper examining wealth distribution patterns across developed nations",
        learned: "Advanced statistical modeling and comparative economic analysis",
        why: "To understand systemic factors driving inequality and propose policy solutions",
      },
    },
    tags: ["research", "economics", "data-analysis"],
    status: "completed",
    category: "academic",
  },
  {
    id: 2,
    content: {
      en: {
        title: "Multilingual chat app",
        description: "Real-time translation for cross-cultural conversations",
        what: "A chat application that translates messages in real-time between users speaking different languages",
        learned: "WebSocket implementation, translation APIs, and state management in complex applications",
        why: "To break down language barriers in online communication",
      },
      vi: {
        title: "Ứng dụng chat đa ngôn ngữ",
        description: "Dịch thời gian thực cho các cuộc trò chuyện liên văn hóa",
        what: "Một ứng dụng chat dịch tin nhắn theo thời gian thực giữa người dùng nói các ngôn ngữ khác nhau",
        learned: "Triển khai WebSocket, API dịch thuật và quản lý trạng thái trong ứng dụng phức tạp",
        why: "Để phá vỡ rào cản ngôn ngữ trong giao tiếp trực tuyến",
      },
      et: {
        title: "Mitmekeelne vestlusrakendus",
        description: "Reaalajas tõlge kultuuridevahelisteks vestlusteks",
        what: "Vestlusrakendus, mis tõlgib sõnumeid reaalajas erinevaid keeli rääkivate kasutajate vahel",
        learned: "WebSocketi rakendamine, tõlke API-d ja oleku haldamine keerukates rakendustes",
        why: "Keelebarjääride murdmiseks veebisuhtluses",
      },
      ru: {
        title: "Многоязычное чат-приложение",
        description: "Перевод в реальном времени для межкультурных бесед",
        what: "Чат-приложение, которое переводит сообщения в реальном времени между пользователями, говорящими на разных языках",
        learned: "Реализация WebSocket, API перевода и управление состоянием в сложных приложениях",
        why: "Преодолеть языковые барьеры в онлайн-общении",
      },
      da: {
        title: "Flersproget chat-app",
        description: "Realtidsoversættelse til tværkulturelle samtaler",
        what: "En chat-applikation, der oversætter beskeder i realtid mellem brugere, der taler forskellige sprog",
        learned: "WebSocket-implementering, oversættelses-API'er og tilstandsstyring i komplekse applikationer",
        why: "At nedbryde sprogbarrierer i online kommunikation",
      },
      tr: {
        title: "Çok dilli sohbet uygulaması",
        description: "Kültürlerarası konuşmalar için gerçek zamanlı çeviri",
        what: "Farklı diller konuşan kullanıcılar arasında mesajları gerçek zamanlı olarak çeviren bir sohbet uygulaması",
        learned: "WebSocket uygulaması, çeviri API'leri ve karmaşık uygulamalarda durum yönetimi",
        why: "Çevrimiçi iletişimde dil engellerini ortadan kaldırmak",
      },
      zh: {
        title: "多语言聊天应用",
        description: "跨文化对话的实时翻译",
        what: "一款聊天应用，可以在说不同语言的用户之间实时翻译消息",
        learned: "WebSocket实现、翻译API以及复杂应用中的状态管理",
        why: "打破在线交流中的语言障碍",
      },
      pl: {
        title: "Wielojęzyczna aplikacja czatu",
        description: "Tłumaczenie w czasie rzeczywistym dla rozmów międzykulturowych",
        what: "Aplikacja czatu, która tłumaczy wiadomości w czasie rzeczywistym między użytkownikami mówiącymi różnymi językami",
        learned: "Implementacja WebSocket, interfejsy API tłumaczeń i zarządzanie stanem w złożonych aplikacjach",
        why: "Aby przełamać bariery językowe w komunikacji online",
      },
      fi: {
        title: "Monikielinen chat-sovellus",
        description: "Reaaliaikainen käännös kulttuurienvälisiin keskusteluihin",
        what: "Chat-sovellus, joka kääntää viestejä reaaliajassa eri kieliä puhuvien käyttäjien välillä",
        learned: "WebSocketin toteutus, käännös-API:t ja tilanhallinta monimutkaisissa sovelluksissa",
        why: "Rikkoutua kielimuurit verkkoviestinnässä",
      },
      sv: {
        title: "Flerspråkig chattapp",
        description: "Översättning i realtid för tvärkulturella konversationer",
        what: "En chattapplikation som översätter meddelanden i realtid mellan användare som talar olika språk",
        learned: "WebSocket-implementering, översättnings-API:er och tillståndshantering i komplexa applikationer",
        why: "Att bryta ner språkbarriärer i onlinekommunikation",
      },
      tok: {
        title: "Multilingual chat app",
        description: "Real-time translation for cross-cultural conversations",
        what: "A chat application that translates messages in real-time between users speaking different languages",
        learned: "WebSocket implementation, translation APIs, and state management in complex applications",
        why: "To break down language barriers in online communication",
      },
    },
    tags: ["react", "node", "i18n", "websockets"],
    status: "in-progress",
    category: "personal",
  },
  {
    id: 3,
    content: {
      en: {
        title: "Climate action platform",
        description: "Connecting activists with local environmental initiatives",
        what: "A platform that maps local environmental projects and connects volunteers with initiatives",
        learned: "Geolocation APIs, community building features, and user engagement strategies",
        why: "To empower local communities to take meaningful climate action",
      },
      vi: {
        title: "Nền tảng hành động khí hậu",
        description: "Kết nối các nhà hoạt động với các sáng kiến môi trường địa phương",
        what: "Một nền tảng lập bản đồ các dự án môi trường địa phương và kết nối tình nguyện viên với các sáng kiến",
        learned: "API định vị địa lý, tính năng xây dựng cộng đồng và chiến lược thu hút người dùng",
        why: "Để trao quyền cho cộng đồng địa phương thực hiện hành động khí hậu có ý nghĩa",
      },
      et: {
        title: "Kliimatoimingute platvorm",
        description: "Ühendab aktiviste kohalike keskkonnaalgatustega",
        what: "Platvorm, mis kaardistab kohalikke keskkonnaprojekte ja ühendab vabatahtlikke algatustega",
        learned: "Geolokatsiooni API-d, kogukonna loomise funktsioonid ja kasutajate kaasamise strateegiad",
        why: "Anda kohalikele kogukondadele võimalus võtta tähenduslikke kliimatoiminguid",
      },
      ru: {
        title: "Платформа климатических действий",
        description: "Соединение активистов с местными экологическими инициативами",
        what: "Платформа, которая отображает местные экологические проекты и соединяет волонтеров с инициативами",
        learned: "API геолокации, функции построения сообщества и стратегии вовлечения пользователей",
        why: "Дать местным сообществам возможность предпринимать значимые действия по борьбе с изменением климата",
      },
      da: {
        title: "Klimahandlingsplatform",
        description: "Forbinder aktivister med lokale miljøinitiativer",
        what: "En platform, der kortlægger lokale miljøprojekter og forbinder frivillige med initiativer",
        learned: "Geolokations-API'er, fællesskabsopbyggende funktioner og brugerengagementsstrategier",
        why: "At give lokale samfund mulighed for at tage meningsfuld klimahandling",
      },
      tr: {
        title: "İklim eylemi platformu",
        description: "Aktivistleri yerel çevre girişimleriyle buluşturma",
        what: "Yerel çevre projelerini haritalayan ve gönüllüleri girişimlerle buluşturan bir platform",
        learned: "Coğrafi konum API'leri, topluluk oluşturma özellikleri ve kullanıcı katılım stratejileri",
        why: "Yerel toplulukları anlamlı iklim eylemi gerçekleştirmeleri için güçlendirmek",
      },
      zh: {
        title: "气候行动平台",
        description: "将活动家与当地的环境倡议联系起来",
        what: "一个映射当地环境项目并将志愿者与倡议联系起来的平台",
        learned: "地理定位API、社区建设功能和用户参与策略",
        why: "赋予当地社区采取有意义的气候行动的能力",
      },
      pl: {
        title: "Platforma działań na rzecz klimatu",
        description: "Łączenie aktywistów z lokalnymi inicjatywami środowiskowymi",
        what: "Platforma mapująca lokalne projekty środowiskowe i łącząca wolontariuszy z inicjatywami",
        learned: "Interfejsy API geolokalizacji, funkcje budowania społeczności i strategie angażowania użytkowników",
        why: "Aby umożliwić lokalnym społecznościom podejmowanie znaczących działań na rzecz klimatu",
      },
      fi: {
        title: "Ilmastotoiminta-alusta",
        description: "Yhdistää aktivistit paikallisiin ympäristöaloitteisiin",
        what: "Alusta, joka kartoittaa paikallisia ympäristöprojekteja ja yhdistää vapaaehtoiset aloitteisiin",
        learned: "Geopaikannus-API:t, yhteisön rakentamisen ominaisuudet ja käyttäjien sitouttamisstrategiat",
        why: "Vahvistaa paikallisyhteisöjä ottamaan merkityksellisiä ilmastotoimia",
      },
      sv: {
        title: "Klimataktionsplattform",
        description: "Kopplar samman aktivister med lokala miljöinitiativ",
        what: "En plattform som kartlägger lokala miljöprojekt och kopplar volontärer till initiativ",
        learned: "Geolokaliserings-API:er, funktioner för att bygga gemenskaper och strategier för användarengagemang",
        why: "För att stärka lokala samhällen att vidta meningsfulla klimatåtgärder",
      },
      tok: {
        title: "Climate action platform",
        description: "Connecting activists with local environmental initiatives",
        what: "A platform that maps local environmental projects and connects volunteers with initiatives",
        learned: "Geolocation APIs, community building features, and user engagement strategies",
        why: "To empower local communities to take meaningful climate action",
      },
    },
    tags: ["activism", "community", "react", "maps-api"],
    status: "completed",
    category: "activism",
  },
  {
    id: 4,
    content: {
      en: {
        title: "Economic justice toolkit",
        description: "Resources for understanding and advocating for economic equality",
        what: "An educational resource hub with interactive tools explaining economic concepts and advocacy strategies",
        learned: "Creating accessible educational content and interactive data visualizations",
        why: "To make economic concepts more accessible and support grassroots economic justice movements",
      },
      vi: {
        title: "Bộ công cụ công bằng kinh tế",
        description: "Tài nguyên để hiểu và vận động cho bình đẳng kinh tế",
        what: "Một trung tâm tài nguyên giáo dục với các công cụ tương tác giải thích các khái niệm kinh tế và chiến lược vận động",
        learned: "Tạo nội dung giáo dục dễ tiếp cận và trực quan hóa dữ liệu tương tác",
        why: "Để làm cho các khái niệm kinh tế dễ tiếp cận hơn và hỗ trợ các phong trào công bằng kinh tế cơ sở",
      },
      et: {
        title: "Majandusliku õigluse tööriistakomplekt",
        description: "Ressursid majandusliku võrdõiguslikkuse mõistmiseks ja eestkoste tegemiseks",
        what: "Haridusressursside keskus interaktiivsete tööriistadega, mis selgitavad majanduslikke mõisteid ja eestkoste strateegiaid",
        learned: "Juurdepääsetava haridusliku sisu ja interaktiivsete andmete visualiseerimise loomine",
        why: "Et muuta majanduslikud mõisted paremini kättesaadavaks ja toetada rohujuure tasandi majandusliku õigluse liikumisi",
      },
      ru: {
        title: "Инструментарий экономической справедливости",
        description: "Ресурсы для понимания и защиты экономического равенства",
        what: "Образовательный ресурсный центр с интерактивными инструментами, объясняющими экономические концепции и стратегии защиты",
        learned: "Создание доступного образовательного контента и интерактивной визуализации данных",
        why: "Сделать экономические концепции более доступными и поддержать низовые движения за экономическую справедливость",
      },
      da: {
        title: "Værktøjssæt til økonomisk retfærdighed",
        description: "Ressourcer til at forstå og tale for økonomisk lighed",
        what: "Et uddannelsesressourcecenter med interaktive værktøjer, der forklarer økonomiske begreber og fortalerstrategier",
        learned: "Skabelse af tilgængeligt uddannelsesindhold og interaktive datavisualiseringer",
        why: "At gøre økonomiske begreber mere tilgængelige og støtte græsrodsbevægelser for økonomisk retfærdighed",
      },
      tr: {
        title: "Ekonomik adalet araç seti",
        description: "Ekonomik eşitliği anlamak ve savunmak için kaynaklar",
        what: "Ekonomik kavramları ve savunuculuk stratejilerini açıklayan interaktif araçlar içeren bir eğitim kaynağı merkezi",
        learned: "Erişilebilir eğitim içeriği ve interaktif veri görselleştirmeleri oluşturma",
        why: "Ekonomik kavramları daha erişilebilir hale getirmek ve tabandan ekonomik adalet hareketlerini desteklemek",
      },
      zh: {
        title: "经济正义工具包",
        description: "理解和倡导经济平等的资源",
        what: "一个教育资源中心，提供解释经济概念和倡导策略的互动工具",
        learned: "创建易于访问的教育内容和互动数据可视化",
        why: "使经济概念更易于理解，并支持基层经济正义运动",
      },
      pl: {
        title: "Zestaw narzędzi sprawiedliwości ekonomicznej",
        description: "Zasoby do zrozumienia i popierania równości ekonomicznej",
        what: "Centrum zasobów edukacyjnych z interaktywnymi narzędziami wyjaśniającymi koncepcje ekonomiczne i strategie rzecznictwa",
        learned: "Tworzenie dostępnych treści edukacyjnych i interaktywnych wizualizacji danych",
        why: "Aby uczynić koncepcje ekonomiczne bardziej dostępnymi i wspierać oddolne ruchy na rzecz sprawiedliwości ekonomicznej",
      },
      fi: {
        title: "Taloudellisen oikeudenmukaisuuden työkalupakki",
        description: "Resursseja taloudellisen tasa-arvon ymmärtämiseen ja puolustamiseen",
        what: "Koulutusresurssikeskus, jossa on interaktiivisia työkaluja taloudellisten käsitteiden ja puolustusstrategioiden selittämiseen",
        learned: "Helposti lähestyttävän koulutussisällön ja interaktiivisten tietojen visualisointien luominen",
        why: "Tehdä taloudellisista käsitteistä helpommin lähestyttäviä ja tukea ruohonjuuritason taloudellisen oikeudenmukaisuuden liikkeitä",
      },
      sv: {
        title: "Verktygslåda för ekonomisk rättvisa",
        description: "Resurser för att förstå och förespråka ekonomisk jämlikhet",
        what: "Ett utbildningsresursnav med interaktiva verktyg som förklarar ekonomiska begrepp och påverkansstrategier",
        learned: "Skapa tillgängligt utbildningsinnehåll och interaktiva datavisualiseringar",
        why: "För att göra ekonomiska begrepp mer tillgängliga och stödja gräsrotsrörelser för ekonomisk rättvisa",
      },
      tok: {
        title: "Economic justice toolkit",
        description: "Resources for understanding and advocating for economic equality",
        what: "An educational resource hub with interactive tools explaining economic concepts and advocacy strategies",
        learned: "Creating accessible educational content and interactive data visualizations",
        why: "To make economic concepts more accessible and support grassroots economic justice movements",
      },
    },
    tags: ["education", "activism", "economics"],
    status: "in-progress",
    category: "activism",
  },
  {
    id: 5,
    content: {
      en: {
        title: "Language learning game",
        description: "Gamified approach to learning vocabulary in multiple languages",
        what: "A game that teaches vocabulary through spaced repetition and contextual learning",
        learned: "Game design principles, educational psychology, and language acquisition theory",
        why: "To make language learning more engaging and effective",
      },
      vi: {
        title: "Trò chơi học ngôn ngữ",
        description: "Phương pháp gamification để học từ vựng trong nhiều ngôn ngữ",
        what: "Một trò chơi dạy từ vựng thông qua lặp lại theo khoảng thời gian và học tập theo ngữ cảnh",
        learned: "Nguyên tắc thiết kế trò chơi, tâm lý giáo dục và lý thuyết tiếp thu ngôn ngữ",
        why: "Để làm cho việc học ngôn ngữ hấp dẫn và hiệu quả hơn",
      },
      et: {
        title: "Keeleõppe mäng",
        description: "Mänguline lähenemine mitme keele sõnavara õppimisele",
        what: "Mäng, mis õpetab sõnavara hajutatud kordamise ja kontekstuaalse õppimise kaudu",
        learned: "Mängudisaini põhimõtted, hariduspsühholoogia ja keele omandamise teooria",
        why: "Et muuta keeleõpe kaasahaaravamaks ja tõhusamaks",
      },
      ru: {
        title: "Игра для изучения языков",
        description: "Игровой подход к изучению словарного запаса на нескольких языках",
        what: "Игра, которая обучает словарному запасу через интервальное повторение и контекстное обучение",
        learned: "Принципы дизайна игр, образовательная психология и теория усвоения языка",
        why: "Сделать изучение языка более увлекательным и эффективным",
      },
      da: {
        title: "Sprogindlæringsspil",
        description: "Gamificeret tilgang til at lære ordforråd på flere sprog",
        what: "Et spil, der underviser i ordforråd gennem fordelt gentagelse og kontekstuel læring",
        learned: "Principper for spildesign, uddannelsespsykologi og sprogindlæringsteori",
        why: "At gøre sprogindlæring mere engagerende og effektiv",
      },
      tr: {
        title: "Dil öğrenme oyunu",
        description: "Birden fazla dilde kelime öğrenmeye yönelik oyunlaştırılmış yaklaşım",
        what: "Aralıklı tekrar ve bağlamsal öğrenme yoluyla kelime öğreten bir oyun",
        learned: "Oyun tasarım ilkeleri, eğitim psikolojisi ve dil edinim teorisi",
        why: "Dil öğrenmeyi daha ilgi çekici ve etkili hale getirmek",
      },
      zh: {
        title: "语言学习游戏",
        description: "通过游戏化方法学习多种语言的词汇",
        what: "一款通过间隔重复和情境学习教授词汇的游戏",
        learned: "游戏设计原则、教育心理学和语言习得理论",
        why: "使语言学习更有趣和有效",
      },
      pl: {
        title: "Gra do nauki języków",
        description: "Grywalizowane podejście do nauki słownictwa w wielu językach",
        what: "Gra, która uczy słownictwa poprzez powtarzanie z odstępami i naukę kontekstową",
        learned: "Zasady projektowania gier, psychologia edukacyjna i teoria nabywania języków",
        why: "Aby uczynić naukę języków bardziej angażującą i skuteczną",
      },
      fi: {
        title: "Kielenoppimispeli",
        description: "Pelaamiseen perustuva lähestymistapa sanaston oppimiseen useilla kielillä",
        what: "Peli, joka opettaa sanastoa hajautetun toiston ja kontekstuaalisen oppimisen kautta",
        learned: "Pelisuunnittelun periaatteet, kasvatustiede ja kielen omaksumisen teoria",
        why: "Tehdä kielenoppimisesta kiinnostavampaa ja tehokkaampaa",
      },
      sv: {
        title: "Språkinlärningsspel",
        description: "Spelifierat tillvägagångssätt för att lära sig ordförråd på flera språk",
        what: "Ett spel som lär ut ordförråd genom spridd repetition och kontextuellt lärande",
        learned: "Speldesignprinciper, utbildningspsykologi och språkförvärvsteori",
        why: "För att göra språkinlärning mer engagerande och effektiv",
      },
      tok: {
        title: "Language learning game",
        description: "Gamified approach to learning vocabulary in multiple languages",
        what: "A game that teaches vocabulary through spaced repetition and contextual learning",
        learned: "Game design principles, educational psychology, and language acquisition theory",
        why: "To make language learning more engaging and effective",
      }
    },
    tags: ["javascript", "linguistics", "education", "game"],
    status: "planned",
    category: "personal",
  },
  {
    id: 6,
    content: {
      en: {
        title: "Chaos theory visualization",
        description: "Interactive exploration of chaos theory principles",
        what: "An interactive web application visualizing chaos theory concepts like the butterfly effect",
        learned: "Advanced canvas manipulation, mathematical modeling, and interactive visualization techniques",
        why: "To make complex mathematical concepts more intuitive and accessible",
      },
      vi: {
        title: "Trực quan hóa lý thuyết hỗn loạn",
        description: "Khám phá tương tác các nguyên tắc của lý thuyết hỗn loạn",
        what: "Một ứng dụng web tương tác trực quan hóa các khái niệm lý thuyết hỗn loạn như hiệu ứng cánh bướm",
        learned: "Thao tác canvas nâng cao, mô hình hóa toán học và kỹ thuật trực quan hóa tương tác",
        why: "Để làm cho các khái niệm toán học phức tạp trở nên trực quan và dễ tiếp cận hơn",
      },
      et: {
        title: "Kaosteooria visualiseerimine",
        description: "Kaosteooria põhimõtete interaktiivne uurimine",
        what: "Interaktiivne veebirakendus, mis visualiseerib kaosteooria kontseptsioone, nagu liblikamõju",
        learned: "Täpsem canvas-manipulatsioon, matemaatiline modelleerimine ja interaktiivse visualiseerimise tehnikad",
        why: "Et muuta keerukad matemaatilised kontseptsioonid intuitiivsemaks ja paremini kättesaadavaks",
      },
      ru: {
        title: "Визуализация теории хаоса",
        description: "Интерактивное исследование принципов теории хаоса",
        what: "Интерактивное веб-приложение, визуализирующее концепции теории хаоса, такие как эффект бабочки",
        learned: "Продвинутые манипуляции с холстом, математическое моделирование и методы интерактивной визуализации",
        why: "Сделать сложные математические концепции более интуитивно понятными и доступными",
      },
      da: {
        title: "Visualisering af kaosteori",
        description: "Interaktiv udforskning af kaosteoriprincipper",
        what: "En interaktiv webapplikation, der visualiserer kaosteoribegreber som sommerfugleeffekten",
        learned: "Avanceret canvas-manipulation, matematisk modellering og interaktive visualiseringsteknikker",
        why: "At gøre komplekse matematiske begreber mere intuitive og tilgængelige",
      },
      tr: {
        title: "Kaos teorisi görselleştirmesi",
        description: "Kaos teorisi ilkelerinin interaktif keşfi",
        what: "Kelebek etkisi gibi kaos teorisi kavramlarını görselleştiren interaktif bir web uygulaması",
        learned: "Gelişmiş canvas manipülasyonu, matematiksel modelleme ve interaktif görselleştirme teknikleri",
        why: "Karmaşık matematiksel kavramları daha sezgisel ve erişilebilir hale getirmek",
      },
      zh: {
        title: "混沌理论可视化",
        description: "混沌理论原理的互动探索",
        what: "一个互动式网络应用，展示混沌理论概念，如蝴蝶效应",
        learned: "高级画布操作、数学建模和互动可视化技术",
        why: "使复杂的数学概念更直观和易于理解",
      },
      pl: {
        title: "Wizualizacja teorii chaosu",
        description: "Interaktywne badanie zasad teorii chaosu",
        what: "Interaktywna aplikacja internetowa wizualizująca koncepcje teorii chaosu, takie jak efekt motyla",
        learned: "Zaawansowana manipulacja płótnem, modelowanie matematyczne i techniki interaktywnej wizualizacji",
        why: "Aby uczynić skomplikowane koncepcje matematyczne bardziej intuicyjnymi i dostępnymi",
      },
      fi: {
        title: "Kaaosteorian visualisointi",
        description: "Kaaosteorian periaatteiden interaktiivinen tutkiminen",
        what: "Interaktiivinen verkkosovellus, joka visualisoi kaaosteorian käsitteitä, kuten perhosen vaikutusta",
        learned: "Edistynyt canvas-manipulointi, matemaattinen mallinnus ja interaktiivisen visualisoinnin tekniikat",
        why: "Tehdä monimutkaisista matemaattisista käsitteistä intuitiivisempia ja helpommin lähestyttäviä",
      },
      sv: {
        title: "Visualisering av kaosteori",
        description: "Interaktiv utforskning av kaosteoriprinciper",
        what: "En interaktiv webbapplikation som visualiserar kaosteorikoncept som fjärilseffekten",
        learned: "Avancerad canvas-manipulation, matematisk modellering och interaktiva visualiseringstekniker",
        why: "För att göra komplexa matematiska koncept mer intuitiva och tillgängliga",
      },
      tok: {
        title: "Chaos theory visualization",
        description: "Interactive exploration of chaos theory principles",
        what: "An interactive web application visualizing chaos theory concepts like the butterfly effect",
        learned: "Advanced canvas manipulation, mathematical modeling, and interactive visualization techniques",
        why: "To make complex mathematical concepts more intuitive and accessible",
      },
    },
    tags: ["mathematics", "visualization", "canvas"],
    status: "in-progress",
    category: "academic",
  },
  {
    id: 7,
    content: {
      en: {
        title: "Secret cat project",
        description: "Something mysterious involving cats...",
        what: "A highly experimental project exploring feline-inspired algorithms",
        learned: "Cutting-edge AI techniques and unconventional problem-solving approaches",
        why: "Because cats are the ultimate inspiration for chaos and creativity",
      },
      vi: {
        title: "Dự án mèo bí mật",
        description: "Điều gì đó bí ẩn liên quan đến mèo...",
        what: "Một dự án thử nghiệm cao cấp khám phá các thuật toán lấy cảm hứng từ mèo",
        learned: "Kỹ thuật AI tiên tiến và cách tiếp cận giải quyết vấn đề phi truyền thống",
        why: "Bởi vì mèo là nguồn cảm hứng tối thượng cho sự hỗn loạn và sáng tạo",
      },
      et: {
        title: "Salajane kassiprojekt",
        description: "Midagi salapärast, mis hõlmab kasse...",
        what: "Kõige eksperimentaalsem projekt, mis uurib kassidest inspireeritud algoritme",
        learned: "Tipptasemel tehisintellekti tehnikad ja ebatraditsioonilised probleemide lahendamise lähenemisviisid",
        why: "Sest kassid on kaose ja loovuse ülim inspiratsioon",
      },
      ru: {
        title: "Секретный кошачий проект",
        description: "Что-то таинственное, связанное с кошками...",
        what: "Высокоэкспериментальный проект, исследующий алгоритмы, вдохновленные кошками",
        learned: "Передовые методы ИИ и нетрадиционные подходы к решению проблем",
        why: "Потому что кошки — это главное вдохновение для хаоса и творчества",
      },
      da: {
        title: "Hemmeligt katteprojekt",
        description: "Noget mystisk med katte...",
        what: "Et højst eksperimentelt projekt, der udforsker katteinspirerede algoritmer",
        learned: "Banebrydende AI-teknikker og ukonventionelle problemløsningstilgange",
        why: "Fordi katte er den ultimative inspiration for kaos og kreativitet",
      },
      tr: {
        title: "Gizli kedi projesi",
        description: "Kedilerle ilgili gizemli bir şey...",
        what: "Kedi ilhamlı algoritmaları keşfeden son derece deneysel bir proje",
        learned: "En son AI teknikleri ve alışılmadık problem çözme yaklaşımları",
        why: "Çünkü kediler kaos ve yaratıcılık için nihai ilham kaynağıdır",
      },
      zh: {
        title: "秘密猫项目",
        description: "涉及猫的神秘事物...",
        what: "一个高度实验性的项目，探索受猫启发的算法",
        learned: "尖端的人工智能技术和非常规的问题解决方法",
        why: "因为猫是混沌和创造力的终极灵感",
      },
      pl: {
        title: "Tajny projekt kotów",
        description: "Coś tajemniczego związanego z kotami...",
        what: "Wysoce eksperymentalny projekt eksplorujący algorytmy inspirowane kotami",
        learned: "Nowatorskie techniki AI i niekonwencjonalne podejścia do rozwiązywania problemów",
        why: "Ponieważ koty są ostateczną inspiracją dla chaosu i kreatywności",
      },
      fi: {
        title: "Salainen kissaprojekti",
        description: "Jotain salaperäistä, joka liittyy kissoihin...",
        what: "Erittäin kokeellinen projekti, joka tutkii kissoista inspiroituja algoritmeja",
        learned: "Huipputason tekoälytekniikat ja epätavalliset ongelmanratkaisumenetelmät",
        why: "Koska kissat ovat kaaoksen ja luovuuden lopullinen inspiraatio",
      },
      sv: {
        title: "Hemligt kattprojekt",
        description: "Något mystiskt som involverar katter...",
        what: "Ett mycket experimentellt projekt som utforskar kattinspirerade algoritmer",
        learned: "Banbrytande AI-tekniker och okonventionella problemlösningsmetoder",
        why: "För att katter är den ultimata inspirationen för kaos och kreativitet",
      },
      tok: {
        title: "Secret cat project",
        description: "Something mysterious involving cats...",
        what: "A highly experimental project exploring feline-inspired algorithms",
        learned: "Cutting-edge AI techniques and unconventional problem-solving approaches",
        why: "Because cats are the ultimate inspiration for chaos and creativity",
      },
    },
    tags: ["experimental", "cats", "ai"],
    status: "planned",
    category: "personal",
    hidden: true,
  },
]
