// Uses page types

export type UsesCategory = {
  title: string
  icon: string  // Icon name for Lucide
  items: {
    name: string
    descriptionKey: string
    description?: string
    link?: string
  }[]
  subsections?: {
    title: string
    icon?: string
    items: {
      name: string
      descriptionKey?: string
      description?: string
      link?: string
    }[]
  }[]
}

// i18n descriptions for uses items
export const usesDescriptions: Record<string, Record<string, string>> = {
  "en": {
    "ryzen": "AMD Ryzen 5 4500U, 8GB RAM, 512GB SSD",
    "externalHDD": "Portable external hard drive for backups",
    "mechanicalKeyboard": "Hot-swappable mechanical keyboard with RGB",
    "wirelessMouse": "Wireless gaming mouse with LIGHTSPEED technology",
    "mainPhone": "Main daily driver smartphone",
    "secondaryPhone": "Secondary phone for testing and development",
    "smartwatch": "Fitness tracking and notifications",
    "primaryEarbuds": "Primary wireless earbuds with ANC",
    "backupEarbuds": "Backup wireless earbuds",
    "dualBoot": "Dual boot setup for development and daily use",
    "primaryBrowser": "Privacy-focused primary browser",
    "secondaryBrowser": "Chromium-based secondary browser",
    "primaryCodeEditor": "Primary code editor with extensions",
    "terminalEmulators": "Modern terminal emulators",
    "versionControl": "Version control system",
    "apiTesting": "API development and testing",
    "databaseManagement": "Relational database management",
    "codeHosting": "Code hosting and collaboration",
    "webHosting": "Web hosting and deployment",
    "ddosProtection": "CDN and DDoS protection",
    "desktopEmail": "Desktop email client (Thunderbird fork)",
    "emailClient": "Cross-platform email client",
    "domainEmail": "Custom domain email hosting",
    "taskManagement": "Note-taking and task management",
    "calendar": "Calendar and scheduling",
    "timeTracking": "Time tracking for projects",
    "automationTool": "Workflow automation",
    "phoneLinking": "Phone-computer integration",
    "noteTaking": "End-to-end encrypted notes",
    "officeSuite": "Office productivity suite",
    "cloudStorage": "Self-hosted cloud storage",
    "vpn": "VPN service for privacy",
    "passwordManager": "Open-source password manager",
    "twoFactorAuth": "Two-factor authentication app",
    "dnsProvider": "Privacy-focused DNS provider",
    "privacySearch": "Privacy-focused search engine",
    "networkVpn": "Mesh VPN for secure networking",
    "lgFirmware": "LG firmware flashing tool",
    "qualcommFlash": "Qualcomm firmware flash tool",
    "samsungFirmware": "Samsung firmware flashing tool",
    "samsungDownload": "Samsung firmware download tool",
    "iosManagement": "iOS device management tool",
    "geographicSystem": "Open source geographic information system",
    "webOpenstreetmap": "Web-based OpenStreetMap editor",
    "desktopOpenstreetmap": "Desktop OpenStreetMap editor",
    "mobileOpenstreetmap": "Mobile OpenStreetMap editor",
    "mobileContributor": "Mobile map contribution app",
    "communityNavigation": "Community-driven navigation",
    "minecraftClient": "Minecraft performance client",
    "gameDistribution": "PC game distribution platform",
    "gameLauncher": "Game launcher and store",
    "indieMarketplace": "Indie game marketplace",
    "vectorGraphics": "Vector graphics editor",
    "uiUxDesign": "UI/UX design tool",
    "graphicDesign": "Easy graphic design tool",
    "digitalPaintingDesktop": "Digital painting (desktop)",
    "digitalPaintingMobile": "Digital painting (mobile)",
    "photoEditing": "Professional photo editing",
    "openSourceEditor": "Open source image editor",
    "professionalEditor": "Professional video editing",
    "professionalEditorDavinci": "Professional editing & color grading",
    "openSourceVideoEditor": "Open source video editor",
    "videoEditorCapcut": "Quick video editing",
    "subtitleEditor": "Advanced subtitle editor",
    "videoPlayer": "Universal media player",
    "audioEditor": "Open source audio editor",
    "musicStreamingYoutube": "Music streaming service",
    "musicStreamingSpotify": "Music streaming service",
    "videoStreaming": "Video streaming platform"
  },
  "vi": {
    "ryzen": "AMD Ryzen 5 4500U, 8GB RAM, 512GB SSD",
    "externalHDD": "Ổ cứng di động để sao lưu",
    "mechanicalKeyboard": "Bàn phím cơ hot-swap với đèn RGB",
    "wirelessMouse": "Chuột không dây với công nghệ LIGHTSPEED",
    "mainPhone": "Điện thoại chính hàng ngày",
    "secondaryPhone": "Điện thoại phụ để thử nghiệm và phát triển",
    "smartwatch": "Theo dõi sức khỏe và thông báo",
    "primaryEarbuds": "Tai nghe không dây chính có ANC",
    "backupEarbuds": "Tai nghe không dây dự phòng",
    "dualBoot": "Cài đặt dual boot cho phát triển và sử dụng hàng ngày",
    "primaryBrowser": "Trình duyệt chính tập trung vào quyền riêng tư",
    "secondaryBrowser": "Trình duyệt phụ dựa trên Chromium",
    "primaryCodeEditor": "Trình chỉnh sửa mã chính với tiện ích mở rộng",
    "terminalEmulators": "Giả lập terminal hiện đại",
    "versionControl": "Hệ thống quản lý phiên bản",
    "apiTesting": "Phát triển và kiểm thử API",
    "databaseManagement": "Quản lý cơ sở dữ liệu quan hệ",
    "codeHosting": "Lưu trữ mã và cộng tác",
    "webHosting": "Lưu trữ web và triển khai",
    "ddosProtection": "CDN và bảo vệ DDoS",
    "desktopEmail": "Ứng dụng email desktop (nhánh Thunderbird)",
    "emailClient": "Ứng dụng email đa nền tảng",
    "domainEmail": "Lưu trữ email tên miền tùy chỉnh",
    "taskManagement": "Ghi chú và quản lý công việc",
    "calendar": "Lịch và lập kế hoạch",
    "timeTracking": "Theo dõi thời gian cho dự án",
    "automationTool": "Tự động hóa quy trình làm việc",
    "phoneLinking": "Tích hợp điện thoại-máy tính",
    "noteTaking": "Ghi chú mã hóa đầu cuối",
    "officeSuite": "Bộ công cụ văn phòng",
    "cloudStorage": "Lưu trữ đám mây tự host",
    "vpn": "Dịch vụ VPN cho quyền riêng tư",
    "passwordManager": "Trình quản lý mật khẩu mã nguồn mở",
    "twoFactorAuth": "Ứng dụng xác thực hai yếu tố",
    "dnsProvider": "Nhà cung cấp DNS tập trung vào quyền riêng tư",
    "privacySearch": "Công cụ tìm kiếm tập trung vào quyền riêng tư",
    "networkVpn": "VPN mesh cho mạng bảo mật",
    "lgFirmware": "Công cụ flash firmware LG",
    "qualcommFlash": "Công cụ flash firmware Qualcomm",
    "samsungFirmware": "Công cụ flash firmware Samsung",
    "samsungDownload": "Công cụ tải firmware Samsung",
    "iosManagement": "Công cụ quản lý thiết bị iOS",
    "geographicSystem": "Hệ thống thông tin địa lý mã nguồn mở",
    "webOpenstreetmap": "Trình chỉnh sửa OpenStreetMap web",
    "desktopOpenstreetmap": "Trình chỉnh sửa OpenStreetMap desktop",
    "mobileOpenstreetmap": "Trình chỉnh sửa OpenStreetMap di động",
    "mobileContributor": "Ứng dụng đóng góp bản đồ di động",
    "communityNavigation": "Điều hướng cộng đồng",
    "minecraftClient": "Client Minecraft hiệu suất cao",
    "gameDistribution": "Nền tảng phân phối game PC",
    "gameLauncher": "Trình khởi chạy game và cửa hàng",
    "indieMarketplace": "Chợ game indie",
    "vectorGraphics": "Trình chỉnh sửa đồ họa vector",
    "uiUxDesign": "Công cụ thiết kế UI/UX",
    "graphicDesign": "Công cụ thiết kế đồ họa dễ dùng",
    "digitalPaintingDesktop": "Vẽ kỹ thuật số (desktop)",
    "digitalPaintingMobile": "Vẽ kỹ thuật số (di động)",
    "photoEditing": "Chỉnh sửa ảnh chuyên nghiệp",
    "openSourceEditor": "Trình chỉnh sửa ảnh mã nguồn mở",
    "professionalEditor": "Chỉnh sửa video chuyên nghiệp",
    "professionalEditorDavinci": "Chỉnh sửa & chỉnh màu chuyên nghiệp",
    "openSourceVideoEditor": "Trình chỉnh sửa video mã nguồn mở",
    "videoEditorCapcut": "Chỉnh sửa video nhanh",
    "subtitleEditor": "Trình chỉnh sửa phụ đề nâng cao",
    "videoPlayer": "Trình phát đa phương tiện đa năng",
    "audioEditor": "Trình chỉnh sửa âm thanh mã nguồn mở",
    "musicStreamingYoutube": "Dịch vụ phát nhạc trực tuyến",
    "musicStreamingSpotify": "Dịch vụ phát nhạc trực tuyến",
    "videoStreaming": "Nền tảng phát video trực tuyến"
  }
}
