import { generateMetadata as generateMeta } from "@/lib/metadata"
import BadgesClientWrapper from "./BadgesClientWrapper"

export const metadata = generateMeta({
  title: "Web Badges Collection",
  description: "A collection of classic web badges and buttons used on my website.",
  path: "badges",
})

// Badge data - defined on server
const BADGES = [
  {
    id: "personal-badge",
    name: "Jarema Badge",
    src: "/badge.png",
    alt: "Jarema personal badge",
    category: "personal",
    width: 88,
    height: 31,
    url: null,
    description: "My personal web badge",
  },
  {
    id: "humans-txt",
    name: "humans.txt",
    src: "/humanstxt.png",
    alt: "humans.txt",
    category: "validation",
    width: 88,
    height: 31,
    url: "https://jarema.me/humans.txt",
    description: "Information about the humans behind this website",
  },
  {
    id: "valid-rss",
    name: "Valid RSS",
    src: "/valid-rss-rogers.png",
    alt: "Valid RSS",
    category: "validation",
    width: 88,
    height: 31,
    url: "https://jarema.me/rss.xml",
    description: "Valid RSS feed",
  },
  {
    id: "valid-atom",
    name: "Valid Atom",
    src: "/valid-atom.png",
    alt: "Valid Atom Feed",
    category: "validation",
    width: 88,
    height: 31,
    url: "https://jarema.me/atom.xml",
    description: "Valid Atom feed",
  },
  {
    id: "join-logo",
    name: "Join Logo",
    src: "/join_logo.gif",
    alt: "Join Logo",
    category: "web",
    width: 88,
    height: 31,
    url: null,
    description: "Classic web badge",
  },
  {
    id: "bannars",
    name: "Bannars",
    src: "/bannars.gif",
    alt: "The March of Bannars",
    category: "web",
    width: 88,
    height: 31,
    url: null,
    description: "The March of Bannars",
  },
  {
    id: "best-viewed",
    name: "Best Viewed With Eyes",
    src: "/best_viewed_with_eyes.gif",
    alt: "Best Viewed With Eyes",
    category: "web",
    width: 88,
    height: 31,
    url: null,
    description: "Best viewed with eyes",
  },
  {
    id: "people-pledge",
    name: "People Pledge",
    src: "/people_pledge_badge_party_cream_pink_88x31.png",
    alt: "People Pledge",
    category: "web",
    width: 88,
    height: 31,
    url: "https://people.pledge.party/",
    description: "People Pledge badge",
  },
  {
    id: "internet-privacy",
    name: "Internet Privacy Now",
    src: "/internetprivacy.gif",
    alt: "Internet Privacy Now",
    category: "privacy",
    width: 88,
    height: 31,
    url: null,
    description: "Internet Privacy Now",
  },
  {
    id: "no-web3",
    name: "Say No to Web3",
    src: "/saynotoweb3_88x31.gif",
    alt: "Say No to Web3",
    category: "web",
    width: 88,
    height: 31,
    url: "https://yesterweb.org/no-to-web3/",
    description: "Say No to Web3",
  },
  {
    id: "got-html",
    name: "Got HTML",
    src: "/got_html.gif",
    alt: "Got HTML?",
    category: "web",
    width: 88,
    height: 31,
    url: null,
    description: "Got HTML?",
  },
  {
    id: "js-warning",
    name: "JavaScript Warning",
    src: "/js-warning.gif",
    alt: "JavaScript Warning",
    category: "web",
    width: 88,
    height: 31,
    url: null,
    description: "JavaScript Warning",
  },
  {
    id: "fedora",
    name: "Fedora",
    src: "/fedora.gif",
    alt: "Powered by Fedora",
    category: "software",
    width: 88,
    height: 31,
    url: "https://fedoraproject.org/",
    description: "Powered by Fedora",
  },
  {
    id: "firefox",
    name: "Firefox",
    src: "/firefox4.gif",
    alt: "Firefox Browser",
    category: "browsers",
    width: 88,
    height: 31,
    url: "https://www.mozilla.org/en-US/firefox/new/",
    description: "Firefox Browser",
  },
  {
    id: "anything-but",
    name: "Anything But Chrome",
    src: "/anythingbut.gif",
    alt: "Anything But Chrome",
    category: "browsers",
    width: 88,
    height: 31,
    url: null,
    description: "Anything But Chrome",
  },
  {
    id: "bitwarden",
    name: "Bitwarden",
    src: "/bitwarden.gif",
    alt: "Bitwarden Password Manager",
    category: "software",
    width: 88,
    height: 31,
    url: null,
    description: "Bitwarden Password Manager",
  },
]

const CATEGORIES = ["all", "personal", "validation", "browsers", "privacy", "software", "web", "misc"]

export default function BadgesPage() {
  return <BadgesClientWrapper badges={BADGES} categories={CATEGORIES} />
}
